package com.notifiy.noticeboard.ui.screens

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.AccountBalance
import androidx.compose.material.icons.filled.ArrowBack
import androidx.compose.material.icons.filled.ConfirmationNumber
import androidx.compose.material.icons.filled.Email
import androidx.compose.material.icons.filled.LocationOn
import androidx.compose.material.icons.filled.Password
import androidx.compose.material.icons.filled.Phone
import androidx.compose.material.icons.filled.Pin
import androidx.compose.material.icons.filled.Place
import androidx.compose.material.icons.filled.Whatsapp
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.lifecycle.viewmodel.compose.viewModel
import androidx.navigation.NavController
import android.Manifest
import android.content.pm.PackageManager
import android.widget.Toast
import androidx.activity.result.contract.ActivityResultContracts
import androidx.core.app.ActivityCompat
import com.notifiy.noticeboard.data.model.NoticeBoard
import com.notifiy.noticeboard.navigation.Screen
import com.notifiy.noticeboard.utils.hasLocationPermission
import com.notifiy.noticeboard.ui.viewmodel.AuthViewModel
import com.notifiy.noticeboard.ui.viewmodel.YourBoardsViewModel
import com.notifiy.noticeboard.ui.viewmodel.cachedViewModel
import com.notifiy.noticeboard.ui.components.LocationTextField
import com.notifiy.noticeboard.utils.ShowErrorSnackbar
import com.notifiy.noticeboard.utils.ValidationUtils
import com.notifiy.noticeboard.utils.getErrorMessage
import com.notifiy.noticeboard.utils.isValidPhoneNumber
import java.util.*
import kotlin.random.Random

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun CreateBoardScreen(
    navController: NavController,
    authViewModel: AuthViewModel = cachedViewModel(AuthViewModel::class.java)
) {
    var organizationName by remember { mutableStateOf("") }
    var organizationEmail by remember { mutableStateOf("") }
    var organizationLocation by remember { mutableStateOf("") }
    var organizationWhatsapp by remember { mutableStateOf("") }
    var organizationCode by remember { mutableStateOf("") }
    var validationError by remember { mutableStateOf("") }
    var isCreating by remember { mutableStateOf(false) }
    var isGeneratingCode by remember { mutableStateOf(false) }
    var showConfirmationDialog by remember { mutableStateOf(false) }
    var isCodeGenerated by remember { mutableStateOf(false) }

    val authState by authViewModel.authState.collectAsState()
    val currentUser = authState.data
    val context = LocalContext.current
    
    // Location permission launcher
    val permissionLauncher = rememberLauncherForActivityResult(
        ActivityResultContracts.RequestMultiplePermissions()
    ) { permissions ->
        val allGranted = permissions.all { it.value }
        if (allGranted) {
            Toast.makeText(context, "Location permission granted! Please click the location icon again.", Toast.LENGTH_SHORT).show()
        } else {
            Toast.makeText(context, "Location permission denied. Please enter location manually.", Toast.LENGTH_SHORT).show()
        }
    }

    val yourBoardsViewModel: YourBoardsViewModel = cachedViewModel(YourBoardsViewModel::class.java)
    val errorMessage by yourBoardsViewModel.errorMessage.collectAsState()

    val snackbarHostState = remember { SnackbarHostState() }

    // Clear generated code when org name or location changes (only if not already generated)
    LaunchedEffect(organizationName, organizationLocation) {
        if (organizationCode.isNotBlank() && !isCodeGenerated) {
            organizationCode = ""
        }
    }

    // Function to generate smart code based on org name and location (10 characters)
    fun generateSmartCode(orgName: String, location: String): String {
        // Take first 3 letters from org name (uppercase)
        val orgPrefix = orgName.take(3).uppercase().filter { it.isLetter() }
        
        // Take first 3 letters from location (uppercase)
        val locPrefix = location.take(3).uppercase().filter { it.isLetter() }
        
        // Generate 4 random numbers
        val numbers = (1..4).map { Random.nextInt(0, 10) }.joinToString("")
        
        // Combine to make 10 characters: 3 org + 3 location + 4 numbers
        val baseCode = (orgPrefix + locPrefix + numbers).take(10)
        
        // If we don't have enough characters, pad with random letters
        return if (baseCode.length < 10) {
            val remaining = 10 - baseCode.length
            val randomLetters = (1..remaining).map { ('A'..'Z').random() }.joinToString("")
            baseCode + randomLetters
        } else {
            baseCode
        }
    }

    // Check if all required fields are filled
    val areRequiredFieldsFilled = organizationName.isNotBlank() && 
                                 organizationLocation.isNotBlank() && 
                                 organizationEmail.isNotBlank() && 
                                 organizationWhatsapp.isNotBlank()


    // Show error messages
    ShowErrorSnackbar(
        error = errorMessage?.let { getErrorMessage(Exception(it)) },
        snackbarHostState = snackbarHostState,
        onErrorShown = { yourBoardsViewModel.clearError() })

    // Handle validation errors
    LaunchedEffect(validationError) {
        if (validationError.isNotEmpty()) {
            snackbarHostState.showSnackbar(validationError)
            validationError = ""
        }
    }

    Box(
        modifier = Modifier
            .fillMaxSize()
            .background(MaterialTheme.colorScheme.background)
    ) {
        // Content
        LazyColumn(
            modifier = Modifier,
//                .fillMaxSize(),
            contentPadding = PaddingValues(16.dp, 50.dp, 16.dp, 50.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        )
        {
            item {
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.SpaceBetween
                ) {
                    IconButton(onClick = { navController.popBackStack() }) {
                        Icon(
                            Icons.Default.ArrowBack, contentDescription = "Back"
                        )
                    }
                    Text(
                        text = "Create Notice Board", fontWeight = FontWeight.Bold, fontSize = 22.sp
                    )
                    IconButton(onClick = {}) {}
                }
            }
            // Header
            item {
                Card(
                    modifier = Modifier.fillMaxWidth(), colors = CardDefaults.cardColors(
                        containerColor = MaterialTheme.colorScheme.primaryContainer
                    )
                ) {
                    Column(
                        modifier = Modifier.padding(20.dp)
                    ) {
                        Text(
                            text = "Create Your Notice Board",
                            fontSize = 20.sp,
                            fontWeight = FontWeight.Bold,
                            color = MaterialTheme.colorScheme.onPrimaryContainer
                        )
                        Spacer(modifier = Modifier.height(8.dp))
                        Text(
                            text = "Fill up the details to create a new notice board for your institute",
                            fontSize = 14.sp,
                            color = MaterialTheme.colorScheme.onPrimaryContainer.copy(alpha = 0.8f)
                        )
                    }
                }
            }

            // Form Fields
            item {
                OutlinedTextField(
                    value = organizationName,
                    onValueChange = { organizationName = it },
                    label = { Text("Organization Name") },
                    placeholder = { Text("Enter your institute name") },
                    leadingIcon = {
                        Icon(Icons.Default.AccountBalance, contentDescription = null)
                    },
                    modifier = Modifier.fillMaxWidth(),
                    singleLine = true,
                    keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Text)
                )
            }


            item {
                OutlinedTextField(
                    value = organizationEmail,
                    onValueChange = { organizationEmail = it },
                    label = { Text("Organization Email") },
                    placeholder = { Text("contact@yourinstitute.com") },
                    leadingIcon = {
                        Icon(Icons.Default.Email, contentDescription = null)
                    },
                    modifier = Modifier.fillMaxWidth(),
                    singleLine = true,
                    keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Email)
                )
            }

            item {
                LocationTextField(
                    value = organizationLocation,
                    onValueChange = { organizationLocation = it },
                    label = "Organization Location",
                    placeholder = "Enter city, state",
                    onLocationRequested = {
                        permissionLauncher.launch(
                            arrayOf(
                                Manifest.permission.ACCESS_FINE_LOCATION,
                                Manifest.permission.ACCESS_COARSE_LOCATION
                            )
                        )
                    }
                )
            }

            item {
                OutlinedTextField(
                    value = organizationWhatsapp,
                    onValueChange = { 
                        // Limit to exactly 10 digits and only allow numbers
                        val filtered = it.filter { char -> char.isDigit() }
                        if (filtered.length <= 10) {
                            organizationWhatsapp = filtered
                        }
                    },
                    label = { Text("WhatsApp Number (10 digits)") },
                    placeholder = { Text("1234567890") },
                    leadingIcon = {
                        Icon(Icons.Default.Whatsapp, contentDescription = null)
                    },
                    modifier = Modifier.fillMaxWidth(),
                    singleLine = true,
                    keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Phone)
                )
            }

            // Organization Code Field (moved to end)
            item {
                OutlinedTextField(
                    value = organizationCode,
                    onValueChange = { /* Read-only field */ },
                    label = { Text("Organization Code") },
                    placeholder = { Text("Click Generate to create unique code") },
                    leadingIcon = {
                        Icon(Icons.Default.ConfirmationNumber, contentDescription = null)
                    },
                    trailingIcon = {
                        if (!isCodeGenerated) {
                            TextButton(
                                onClick = {
                                    if (areRequiredFieldsFilled) {
                                        showConfirmationDialog = true
                                    } else {
                                        validationError = "Please fill all required fields first"
                                    }
                                },
                                enabled = areRequiredFieldsFilled && !isGeneratingCode
                            ) {
                                if (isGeneratingCode) {
                                    CircularProgressIndicator(
                                        modifier = Modifier.size(16.dp),
                                        strokeWidth = 2.dp
                                    )
                                } else {
                                    Text(
                                        "Generate", 
                                        color = if (areRequiredFieldsFilled) 
                                            MaterialTheme.colorScheme.primary 
                                        else 
                                            MaterialTheme.colorScheme.onSurface.copy(alpha = 0.38f)
                                    )
                                }
                            }
                        } else {
                            // Show generated code is final
                            Text(
                                "✓ Generated ",
                                color = MaterialTheme.colorScheme.primary,
                                style = MaterialTheme.typography.bodySmall,
                                modifier = Modifier.padding(end = 10.dp)
                            )
                        }
                    },
                    modifier = Modifier.fillMaxWidth(),
                    singleLine = true,
                    readOnly = true,
                    enabled = false
                )
            }


            // Authentication Status
            if (currentUser == null) {
                item {
                    Card(
                        modifier = Modifier.fillMaxWidth(), colors = CardDefaults.cardColors(
                            containerColor = MaterialTheme.colorScheme.errorContainer
                        )
                    ) {
                        Text(
                            text = "Please sign in to create a notice board",
                            color = MaterialTheme.colorScheme.onErrorContainer,
                            modifier = Modifier.padding(16.dp),
                            textAlign = TextAlign.Center
                        )
                    }
                }
            }

            // Error/Success Messages
            if (errorMessage?.isNotEmpty() == true) {
                item {
                    Card(
                        modifier = Modifier.fillMaxWidth(), colors = CardDefaults.cardColors(
                            containerColor = MaterialTheme.colorScheme.errorContainer
                        )
                    ) {
                        Text(
                            text = errorMessage ?: "",
                            color = MaterialTheme.colorScheme.onErrorContainer,
                            modifier = Modifier.padding(16.dp),
                            textAlign = TextAlign.Center
                        )
                    }
                }
            }

            // Create Button
            item {
                Button(
                    onClick = {
                        println("DEBUG: CreateBoardScreen - Create button clicked")

                        // Check if user is authenticated
                        if (currentUser == null) {
                            println("DEBUG: CreateBoardScreen - User not authenticated")
                            validationError = "Please sign in to create a notice board"
                            return@Button
                        }

                        println("DEBUG: CreateBoardScreen - User authenticated: ${currentUser.id}")

                        // Validate form
                        if (organizationName.isBlank() || organizationEmail.isBlank() || organizationLocation.isBlank() || organizationWhatsapp.isBlank() || organizationCode.isBlank()) {
                            println("DEBUG: CreateBoardScreen - Form validation failed: empty fields")
                            validationError = "Please fill all fields and generate organization code"
                            return@Button
                        }

                        // Validate email format
                        if (!ValidationUtils.isValidEmail(organizationEmail)) {
                            println("DEBUG: CreateBoardScreen - Email validation failed")
                            validationError = "Please enter a valid email address"
                            return@Button
                        }

                        // Validate WhatsApp number format
                        if (!isValidPhoneNumber(organizationWhatsapp)) {
                            println("DEBUG: CreateBoardScreen - WhatsApp validation failed")
                            validationError =
                                "Please enter a valid 10-digit WhatsApp number"
                            return@Button
                        }

                        println("DEBUG: CreateBoardScreen - Form validation passed")
                        isCreating = true

                        // Create board in Firebase with generated organization code
                        val newBoard = NoticeBoard(
                            id = UUID.randomUUID().toString(),
                            organizationName = organizationName,
                            organizationCode = organizationCode,
                            organizationEmail = organizationEmail,
                            organizationLocation = organizationLocation,
                            organizationWhatsapp = organizationWhatsapp,
                            createdBy = currentUser?.id ?: ""
                        )

                        println("DEBUG: CreateBoardScreen - Calling createNoticeBoard with: $newBoard")

                        yourBoardsViewModel.createNoticeBoard(newBoard) { success, createdBoard ->
                            println("DEBUG: CreateBoardScreen - createNoticeBoard result: $success")
                            isCreating = false
                            if (success && createdBoard != null) {
                                println("DEBUG: CreateBoardScreen - Board created successfully with code: ${createdBoard.organizationCode}")
                                val message = "Notice board \"${organizationName}\" created successfully!\n\nYour organization code: ${createdBoard.organizationCode}\n\nShare this code with others to let them subscribe to your board."
                                Toast.makeText(context, message, Toast.LENGTH_LONG).show()
                                navController.popBackStack()
                            } else {
                                println("DEBUG: CreateBoardScreen - Board creation failed")
                                Toast.makeText(context, "Failed to create notice board. Please try again.", Toast.LENGTH_SHORT).show()
                            }
                        }
                    },
                    modifier = Modifier.fillMaxWidth(),
                    enabled = !isCreating && currentUser != null
                ) {
                    if (isCreating) {
                        CircularProgressIndicator(
                            modifier = Modifier.size(20.dp), color = Color.White
                        )
                    } else {
                        Text(
                            text = "Create Notice Board",
                            fontSize = 16.sp,
                            fontWeight = FontWeight.Medium
                        )
                    }
                }
            }

            // Subscription Info
//            item {
//                Card(
//                    modifier = Modifier.fillMaxWidth(),
//                    colors = CardDefaults.cardColors(
//                        containerColor = MaterialTheme.colorScheme.surfaceVariant
//                    )
//                )
//                {
//                    Column(
//                        modifier = Modifier.padding(16.dp)
//                    ) {
//                        Text(
//                            text = "Subscription Information",
//                            fontSize = 16.sp,
//                            fontWeight = FontWeight.Bold,
//                            color = MaterialTheme.colorScheme.onSurfaceVariant
//                        )
//                        Spacer(modifier = Modifier.height(8.dp))
//                        Text(
//                            text = "Your notice board will be created with a free subscription. You can upgrade to premium later for additional features.",
//                            fontSize = 14.sp,
//                            color = MaterialTheme.colorScheme.onSurfaceVariant.copy(alpha = 0.8f)
//                        )
//                        Spacer(modifier = Modifier.height(12.dp))
//                        Button(
//                            onClick = {
//                                // TODO: Navigate to subscription page
//                            },
//                            modifier = Modifier.fillMaxWidth(),
//                            colors = ButtonDefaults.buttonColors(
//                                containerColor = MaterialTheme.colorScheme.primary
//                            )
//                        ) {
//                            Text("View Subscription Plans")
//                        }
//                    }
//                }
//            }
        }

        // Snackbar Host
        SnackbarHost(
            hostState = snackbarHostState,
            modifier = Modifier
                .align(Alignment.BottomCenter)
                .padding(bottom = 40.dp)
        )

        // Confirmation Dialog
        if (showConfirmationDialog) {
            AlertDialog(
                onDismissRequest = { showConfirmationDialog = false },
                title = { Text("Confirm Details") },
                text = { 
                    Text("Please review your details carefully:\n\n" +
                         "Organization: $organizationName\n" +
                         "Location: $organizationLocation\n" +
                         "Email: $organizationEmail\n" +
                         "WhatsApp: $organizationWhatsapp\n\n" +
                         "We will generate a unique 10-character code based on your organization name and location. " +
                         "This code cannot be changed once generated.")
                },
                confirmButton = {
                    TextButton(
                        onClick = {
                            showConfirmationDialog = false
                            isGeneratingCode = true
                            // Generate code based on org name and location
                            val generatedCode = generateSmartCode(organizationName, organizationLocation)
                            organizationCode = generatedCode
                            isCodeGenerated = true
                            isGeneratingCode = false
                        }
                    ) {
                        Text("Continue")
                    }
                },
                dismissButton = {
                    TextButton(
                        onClick = { showConfirmationDialog = false }
                    ) {
                        Text("Recheck")
                    }
                }
            )
        }

    }
}
